In [7]:
%run D:\valkyrie_shared\python\apps\run_notebook_import.py

In [8]:
from sklearn.cross_decomposition import PLSRegression as PLS
from valkyrie.quants.linear_model import params_from_pls, linear_pred

In [9]:
N = int(5e7)

In [25]:
x1 = np.random.randn(N)
x2 = np.random.randn(N)
z0 = np.random.randn(N)
z1 = np.random.randn(N)
z2 = np.random.randn(N)
z3 = np.random.randn(N)

v11 = x1 + z1 + 0.3
v12 = x1 + z2 - 2.5
v2  = x2 + z3 + 100

y = x1 + 2 * x2 + z0 + 0.5


In [26]:
X = np.c_[v11, v12, v2]

In [27]:
pls = PLS(1)

In [28]:
pls.fit(X,y)

PLSRegression(n_components=1)

In [30]:
y_hat = pls.predict(X)

In [31]:
pls.score(X, y)

0.42868871070238135

In [32]:
pls2 = PLS(2)

In [33]:
pls2.fit(X, y)
pls2.score(X, y)

0.4445896003498033

In [41]:
y_hat2 = pls2.predict(X)

In [39]:
np.std(y * y)

8.833780992852086

In [43]:
np.std(y_hat2 * y_hat2)

4.11233779551684

In [44]:
from sklearn.linear_model import LinearRegression as LR

In [45]:
lr = LR(fit_intercept=True)

In [46]:
lr.fit(X,y)

LinearRegression()

In [47]:
lr.score(X,y)

0.4445896030052676

In [48]:
lr.coef_

array([0.33312761, 0.33361074, 1.00004863])

In [51]:
lr.intercept_

-98.77110861974118

In [49]:
x_coef2

array([0.33321686, 0.33352145, 1.00004864])

In [34]:
x_coef, offset = params_from_pls(pls)

In [52]:
x_coef

array([0.42858021, 0.42880445, 0.85700553])

In [53]:
offset

array([-84.25738791])

In [36]:
x_coef2, offset2 = params_from_pls(pls2)

In [50]:
offset2

array([-98.77135971])

In [38]:
y_hat2 = linear_pred(V, x_coef, offset)

NameError: name 'V' is not defined

In [ ]:
np.sum(np.abs(y_hat.reshape(-1)-y_hat2.reshape(-1)))